### ISSUE TITLE
Confusion about this subgraph

### ISSUE THREAD

**Issue by JohannesHoppe** [ianlapham/uniswap-subgraph-v2#7]
Can you please explain what the difference is between this repository here and the official [Uniswap repository](https://github.com/Uniswap/uniswap-v2-subgraph)?

The data on https://thegraph.com/explorer/subgraph/ianlapham/uniswapv2 and https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2 look the same at a first glance.

Thanks a lot! 🙂 👍

**Comment by ianlapham** [comment]
So the data actually is the same - they are both pointing to the same indexed data in their DB. I use that personal one for testing sometimes, and if it syncs they update the official one to point to the same data as well. 

You should always refer to the official one as the production version. .

**Comment by JohannesHoppe** [comment]
Thanks!
